- id: azure-gpt-41-mini
  type: azure_chat
  model: gpt-4.1-mini
  api_key:
  api_version: 2024-05-01-preview
  azure_deployment: gpt-41-mini
  endpoint: "<your-endpoint>"
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
- id: oai-gpt-41
  type: openai_chat
  model: gpt-4.1
  api_key:
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
- id: oai-gpt-41-mini
  type: openai_chat
  model: gpt-4.1-mini
  api_key:
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
- id: oai-gpt-41-nano
  type: openai_chat
  model: gpt-4.1-nano
  api_key:
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
- id: azure-embedding-large
  type: azure_embedding
  model: text-embedding-3-large
  api_key:
  api_version: "2023-05-15T00:00:00.000Z"
  azure_deployment: te-3-large
  endpoint: "<your-endpoint>"
  cost_per_million_input_token: 0.13
- id: oai-embedding-small
  type: openai_embedding
  model: text-embedding-3-small
  api_key:
  api_version: 2024-02-15-preview
  cost_per_million_input_token: 0.02
- id: cohere
  type: cohere_azure
  model: "rerank-multilingual-v3.5"
  api_key:
  endpoint: "your_cohere-endpoint"
  cost_per_1k_requests: 2
- id: gemma3
  type: ollama
  model: gemma3:27b
  host: https://gpu.aet.cit.tum.de/ollama
  api_key: ""
  cost_per_million_input_token: 0
  cost_per_million_output_token: 0
- id: gpt-oss
  type: ollama
  model: gpt-oss:120b
  host: https://gpu.aet.cit.tum.de/ollama
  api_key: ""
  cost_per_million_input_token: 0
  cost_per_million_output_token: 0
- id: mxbai-embed-large
  type: ollama
  model: mxbai-embed-large:latest
  host: https://gpu.aet.cit.tum.de/ollama
  api_key: ""
  cost_per_million_input_token: 0
  cost_per_million_output_token: 0
- id: nomic-embed-text
  type: ollama
  model: nomic-embed-text:latest
  host: https://gpu.aet.cit.tum.de/ollama
  api_key: ""
  cost_per_million_input_token: 0
  cost_per_million_output_token: 0
