- api_key:
  api_version: 2024-05-01-preview
  azure_deployment: gpt-41-mini
  description: GPT 4.1 Mini on Azure
  endpoint: "<your-endpoint>"
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
  id: azure-gpt-41-mini
  model: gpt-4.1-mini
  name: GPT 4.1 Mini
  type: azure_chat
- api_key:
  description: GPT 4.1
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
  id: oai-gpt-41
  model: gpt-4.1
  name: GPT 4.1
  type: openai_chat
- api_key:
  description: GPT 4.1 Mini
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
  id: oai-gpt-41-mini
  model: gpt-4.1-mini
  name: GPT 4.1 Mini
  type: openai_chat
- api_key:
  description: GPT 4.1 Nano
  cost_per_million_input_token: 0.4
  cost_per_million_output_token: 1.6
  id: oai-gpt-41-nano
  model: gpt-4.1-nano
  name: GPT 4.1 Nano
  type: openai_chat
- api_key:
  api_version: "2023-05-15T00:00:00.000Z"
  azure_deployment: te-3-large
  description: Embedding Large 8k Azure
  endpoint: "<your-endpoint>"
  cost_per_million_input_token: 0.13
  id: azure-embedding-large
  model: text-embedding-3-large
  name: Embedding Large
  type: azure_embedding
- api_key:
  api_version: 2024-02-15-preview
  description: Embedding Small 8k
  cost_per_million_input_token: 0.02
  id: oai-embedding-small
  model: text-embedding-3-small
  name: Embedding Small
  type: openai_embedding
- api_key:
  description: Cohere V2 client
  endpoint: "your_cohere-endpoint"
  model: "rerank-multilingual-v3.5"
  cost_per_1k_requests: 2
  id: cohere
  name: Cohere Client V2
  type: cohere_azure
- api_key:
  api_version: 2024-02-15-preview
  azure_deployment: whisper
  description: Azure Whisper for transcription
  endpoint: "<your-endpoint>"
  id: azure-whisper
  model: whisper
  name: Azure Whisper
  type: azure_whisper
- api_key:
  description: OpenAI Whisper for transcription
  id: oai-whisper
  model: whisper-1
  name: OpenAI Whisper
  type: openai_whisper
