version: '3.8'

# Development version of docker-compose.yml

services:
  athena:
    build: ./athena
    image: athena
    command: echo "Athena build succeeded, exiting (this is normal)"

  llm_core:
      build:
        context: ./llm_core
        additional_contexts:
          athena: service:athena
      depends_on:
        - athena
      image: llm_core
      command: echo "llm_core build succeeded, exiting (this is normal)"

  assessment_module_manager:
    build:
      context: ./assessment_module_manager
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5100:5100"
    volumes:
      - ./assessment_module_manager/deployments.ini:/code/deployments.ini:ro

  module_example:
    hostname: module-example
    build:
      context: modules/programming/module_example
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5001:5001"

  module_programming_llm:
    hostname: module-programming-llm
    build:
      context: modules/programming/module_programming_llm
      additional_contexts:
        athena: service:athena
        llm_core: service:llm_core
    depends_on:
      - athena
      - llm_core
    ports:
      - "5002:5002"

  module_text_llm:
    hostname: module-text-llm
    build:
      context: modules/text/module_text_llm
      additional_contexts:
        athena: service:athena
        llm_core: service:llm_core
    depends_on:
      - athena
      - llm_core
    ports:
      - "5003:5003"

  module_text_cofee:
    hostname: module-text-cofee
    build:
      context: modules/text/module_text_cofee
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5004:5004"

  module_programming_themisml:
    hostname: module-programming-themisml
    build:
      context: modules/programming/module_programming_themisml
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5005:5005"

  module_programming_apted:
    hostname: module-programming-apted
    build:
      context: modules/programming/module_programming_apted
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5006:5006"

  module_modeling_llm:
    hostname: module-modeling-llm
    build:
      context: modules/modeling/module_modeling_llm
      additional_contexts:
        athena: service:athena
        llm_core: service:llm_core
    depends_on:
      - athena
      - llm_core
    ports:
      - "5008:5008"

  module_programming_winnowing:
    hostname: module-programming-winnowing
    build:
      context: modules/programming/module_programming_winnowing
      additional_contexts:
        athena: service:athena
    depends_on:
      - athena
    ports:
      - "5009:5009"
